### ISSUE TITLE
Unhelpful/Non-existent publish error message when Exchange does not exist on RabbitMQ

### ISSUE THREAD

**Issue by kowi1** [rabbitmq/rabbitmq-dotnet-client#1000]
channel.BasicPublish(exchange: "counter", routingKey: "counter", body: messageBody, basicProperties: null);

When the exchange "counter" has not been created on rabbitmq, no error is thrown to show this.The alternative is to check for the existence of the exchange before publishing.

Ideally an error should be thrown by rabbitmq client when an exchange does not exist.

**Comment by lukebakken** [comment]
This is the default behavior for RabbitMQ and client applications and it does surprise users. In order to be certain your message is published, you *must* use the `mandatory` flag and publisher confirmations.

https://www.rabbitmq.com/confirms.html#publisher-confirms
https://www.rabbitmq.com/reliability.html#routing
https://www.rabbitmq.com/tutorials/tutorial-seven-dotnet.html

**Comment by michaelklishin** [comment]
As well as https://www.rabbitmq.com/publishers.html#unroutable
