### ISSUE TITLE
DequeueNowait returns null first time.

### ISSUE THREAD

**Issue by tomstaijen** [rabbitmq/rabbitmq-dotnet-client#13]
Is it possible that DequeueNowait will return nothing the first time because no data has been prefetched yet, even when there are messages on the queue? 

If I use Dequeue with a wait time of 10ms i do get a message the first time. 

If this is possible, is it by design? Or is there a workaround other then using a wait period?

I'm using 2.8.7 client.

**Comment by michaelklishin** [comment]
@cvanbergen thanks for confirming!

**Comment by kjnilsson** [comment]
Hi @tomstaijen, @rbanderton, @cvanbergen,

I think it is time to finally bring this issue to a close. As @hyperthunk observed a few years ago this is a naturally occurring race. The Queue property exposed on QueueingBasicConsumer does not provide direct access to the remote RabbitMQ queue. It is a local buffer to which messages are asynchronously delivered which is why there is a delay, however slight. If you want direct access to the remote queue the simplest approach is to use the 'BasicGet' method on the `Model` instance. Yes it is slower but it is more intuitive.

Ultimately I don't think QueueingBasicConsumer is a helpful abstraction and have issued a PR to deprecate it in favour of `EventingBasicConsumer` and the `Subscription` class in the `RabbitMQ.Client.MessagePatterns` namespace. Once that PR is merged I think we can close this issue.  

Cheers
Karl

**Comment by michaelklishin** [comment]
#173 is in.
