### ISSUE TITLE
ClientArrayPool tracking is already supported by ArrayPool

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1421]
@danielmarbach points out [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1347#discussion_r1396380470) that `ArrayPool` provides tracking capabilities so we probably don't need `ClientArrayPool`.

**Comment by danielmarbach** [comment]
I did not suggest to use MemoryPool instead in the comment linked. My point was that the code that previously used ArrayPool could be instrumented by leveraging the event source. As far as I understand the ClientArrayPool has tracking code.

I've also made another comment about the larger problem probably not being addressed since disposing the buffers was essentially just moved to a different path.

**Comment by lukebakken** [comment]
> My point was that the code that previously used ArrayPool could be instrumented by leveraging the event source. As far as I understand the ClientArrayPool has tracking code.

OK, I see. I will adjust this issue to reflect that.

I have addressed the "larger problem". Thanks for pointing that out!
