### ISSUE TITLE
EventingBasicConsumer Shutdown event fires twice

### ISSUE THREAD

**Issue by Nicholi** [rabbitmq/rabbitmq-dotnet-client#144]
Was just hooking into the events and noticed the Shutdown event fires twice for EventingBasicConsumer. Unsure if this is known/desired behavior or a bug.

Here is a quick sample. Nothing special or out of the ordinary imo.
Using latest client as of this writing, 3.5.6.

```csharp
    var connectionFactory = new ConnectionFactory();
    connectionFactory.Uri = "amqp://user:pass@localhost:5672/dev";
    var mqExchange = "devExchange";
    var mqQueue = "devQueue";
    var mqQueueRouteKey = "rk_devQueue";

    using (var mqConn = connectionFactory.CreateConnection())
    using (var listenChannel = mqConn.CreateModel())
    {
        mqConn.ConnectionShutdown += (o, a) => Console.WriteLine("Connection Shutdown");
        listenChannel.ModelShutdown += (o, a) => Console.WriteLine("Model Shutdown");

        listenChannel.ExchangeDeclare(mqExchange, ExchangeType.Direct, true, false, null);
        listenChannel.QueueDeclare(mqQueue, true, false, false, null);
        listenChannel.QueueBind(mqQueue, mqExchange, mqQueueRouteKey, null);

        var consumer = new EventingBasicConsumer(listenChannel);
        consumer.Shutdown += (o, a) => Console.WriteLine("Consumer Shutdown");
        String consumerTag = listenChannel.BasicConsume(mqQueue, false, consumer);

        // same happens if you just let the using dispose statements close the connection
        mqConn.Close();
    }
```

Output is:
```
Model Shutdown
Consumer Shutdown
Consumer Shutdown
Connection Shutdown
Press any key to continue . . .
```

**Comment by michaelklishin** [comment]
Thank you for providing a way to reproduce.

**Comment by eiver** [comment]
ConsumerCancelled from DefaultBasicConsumer also fires twice

**Comment by hairyhum** [comment]
Event is being added to `ModelShutdown` event to be called in [OnModuleShutdown](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs#L660)

And also it's called from `ConsumerDispatcher.HandleModelShutdown` which is called from `BroadcastShutdownToConsumers` on the [next line](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs#L661).

I don't have much knowledge about eventing model in dotnet client, but it looks like consumers `HandleModelShutdown` should not be [added to ModelShutdown](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs#L1184) 
Since it's already being notified from consumer dispatcher.

**Comment by michaelklishin** [comment]
@hairyhum consumer's shutdown event handlers are not supposed to be registered for channels, your understanding is correct

**Comment by michaelklishin** [comment]
Thank you for looking into this, @hairyhum. This was accidentally introduced in a monster community member patch in https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/795a718c1973f418ce7f6adac866ae587b03a4db.
