### ISSUE TITLE
Decouple client releases from RabbitMQ releases

### ISSUE THREAD

**Issue by danielmarbach** [rabbitmq/rabbitmq-dotnet-client#150]
Currently this library follows the release version number of the broker. While this seems to make sense I think it is actually more harmful than helpful for clients and the maintainers of the library because it is really hard to convey breaking changes or not accidentally introduce breaking changes. Here is a proposal:
- Decouple the client version from the broker version, i.ex. when we move to async/await bump the major version to 4.0.0 and from then on follow the new versioning scheme
- Follow [Semantic Versioning](http://semver.org/)
- Internalize protocol implementations, Frames and low level infrastructure, make only public what needs to be public
- Introduce [ApiApprovals](https://github.com/JakeGinnivan/ApiApprover) to verify that no-accidental breaking changes are introduced
- Optionally consider [GitVersion](https://github.com/GitTools/GitVersion) to simplify versioning of the library
- Optionally consider [Semantic Release Notes](http://www.semanticreleasenotes.org/) or [Release Notes Compiler](https://github.com/GitTools/GitReleaseNotes) to auto generate proper release notes

**Comment by michaelklishin** [comment]
We are considering decoupling client library releases from server releases. That should happen one way or another for the next RabbitMQ release (which is some 8-9 months away).

RabbitMQ largely follows semantic versioning (which suffers from the "no true Scotsman" fallacy) but sometimes fixing bugs or serious usability issues means introducing breaking changes. We also try shipping small non-breaking features in point releases if we can to get them out faster.

I agree with the premise of this issue but now sure what the acceptance criteria should be.

**Comment by michaelklishin** [comment]
Also, we appreciate the advice on what tooling we can adopt.

**Comment by danielmarbach** [comment]
I used all the tools noted here in prod. I can defintely help

**Comment by Jestar342** [comment]
RabbitMQ doesn't follow Semantic Versioning as demonstrated by the issue #98 where the "immediate" parameter was removed, thus breaking backward's compatibility - but maintaining the binding redirect for versions that expect the method to exist. This results in the error: 

Method not found: 'Void RabbitMQ.Client.IModel.BasicPublish(System.String, System.String, Boolean, Boolean, RabbitMQ.Client.IBasicProperties, Byte[])'

Removing a parameter is a breaking change, and to be told it isn't an "actual major change" in the locking comment of an is quite insulting.

**Comment by michaelklishin** [comment]
@Jestar342 as I explained in #98, the feature was **dropped in RabbitMQ server over 3 years ago** and the fact that the respective API method wasn't removed was confusing and misleading. Please stop fixating on a method not being found and take a step back: the entire feature had been **absent for over 3 years** by the time we removed the method.

Yes, we sometimes introduce small features in point releases to ship them quicker. We sometimes **have to** break public API to fix an issue, e.g. because language constraints require us to do so (e.g. Java has checked exceptions that cascade). If you think this is not a reasonable versioning scheme, fine.
I'm going to lock this issue again because discussing the pros and cons of semantic versioning is not in scope for this issue.

You are not seeing a forest behind the trees. Get over it.

**Comment by michaelklishin** [comment]
OK, I'm unlocking this because this issue is actually an open ended question right now, so there are things to discuss. I've removed all comments that are irrelevant to what this issue is about.

**Comment by michaelklishin** [comment]
Two things that make a strong case for release decoupling: we are mostly convinced that #83 and #148 are worth doing this year. Both definitely are major API changes and warrant a version bump to 4.0 but going to 4.0 doesn't make sense for RabbitMQ itself and the Java client, for example.

The quickest way to get there would be to exclude this client from the `3.6.2` release (for `3.6.1` it's probably too late) and start publishing releases in this repo on GitHub.

@dumbbell FYI.

**Comment by michaelklishin** [comment]
This has already happened in master: the client has a different version and a NuGet feed of releases. RabbitMQ 3.7.0 milestone releases no longer include this client. `stable` will follow eventually.

**Comment by Jestar342** [comment]
Do I get an apology now? You accused me of not seeing the woods for the
trees, yet all I asked for is exactly what you have eventually implemented.
I was not complaining that you broke API - that is understandable. I was
complaining that you were using/releasing via Nuget, a tool that implements
and has its very core fundamentals based upon SemVer, and *not* telling it
(and thus the users thereof) that you were breaking API because your
versioning strategy was "masking" those changes as minor/insignificant
patches, and all you did was summarily dismiss my posts without any thought
nor decency.

**Comment by kjnilsson** [comment]
Closing as this has been completed.
