### ISSUE TITLE
ConnectionFactory ignoring Port Setting when SSL is Enabled in v3.6.2

### ISSUE THREAD

**Issue by cdemi** [rabbitmq/rabbitmq-dotnet-client#186]
In the latest version (v3.6.2), if you have SSL enabled on `ConnectionFactory` and a Port set, the port being set is ignored and it uses always port 5671

**Comment by kjnilsson** [comment]
Hi @cdemi,

Is this with or without autorecovery enabled?

Cheers
Karl

**Comment by cdemi** [comment]
AutomaticRecoveryEnabled is set to true in my case

**Comment by cdemi** [comment]
I think it would be a good idea to remove this package from NuGet and upload a new version. I'm sure it will save a lot of people some trouble since this is a breaking change!

**Comment by michaelklishin** [comment]
@cdemi it will be in `3.6.3`.

**Comment by cdemi** [comment]
@michaelklishin I know but currently, everyone wanting to use RabbitMQ Client will get the package from NuGet and by default they will get this version since it is the latest

**Comment by michaelklishin** [comment]
@cdemi we do not re-publish packages. Re-publishing packages is a terrible idea. Releasing a new version is the right thing to do and currently for this client it happens in lock step with RabbitMQ releases.

**Comment by cdemi** [comment]
@michaelklishin correct, that's why I suggested to remove (unpublish) `3.6.2` and publish `3.6.3`. This will avoid having people download this version without re-publishing

**Comment by michaelklishin** [comment]
@cdemi look, we get it. Currently this library is published in lock step with the server. This will change some day but today we have what we have (and have had for 10 years).

This issue only affects those who override RabbitMQ ports. The majority of users don't. Those who do can

 * Go to an older release, it will work just fine
 * Build from source, since a fix is already available (and building from source is now easier than before)

Let's move on with our lives.
