### ISSUE TITLE
Forcing connection over IPv6 or IPv4

### ISSUE THREAD

**Issue by pantonis** [rabbitmq/rabbitmq-dotnet-client#226]
Hi,

I have come across the scenario that the library throws a SocketException in SocketFrameHandler constructor when it tries to connect through IPV6. It the successfully connects using IPv4.

This is not a problem most of the times but for low latency systems when memory is important is kind of expensive to throw exception every time a connection is being established, especially when there are a number of connections.

Is it possible to somehow pass the socket address type as parameter to avoid this?

Thanks

**Comment by michaelklishin** [comment]
Can you please provide an example code snippet, library and OS version details?

RabbitMQ connections are supposed to be long lived so I am not buying into the argument that throwing and catching an exception is expensive. If it is then you should be using a memory managed runtime to begin with.

That said, forcing IPv6 or IPv4 is a fairly reasonable request.

**Comment by pantonis** [comment]
I am currently running on Windows 10. 
"RabbitMQ connections are supposed to be long lived" I know that. I was speaking about scenarios that connectivitity is lost due to network problems. Unfortunately in a low latency system I don't have the flexibility to throw exceptions.

**Comment by lloydsparkes** [comment]
I would like to add my support to this issue, to support forcing IPv6 or IPv4 over the other.

In my case its because, Socket.OSSupportsIPv6 returns true. 

Which is correct, because the OS supports IPv6 (Windows 10) and it has a loopback IPv6 address. 

_(As an aside, the Obsolute Socket.SupportsIPv6, returns false, because it does not have a "real" IPv6 network)_

The problem is, that the server it is trying to connect to can only be connected to over IPv4. To get around this I have just built my own tweaked version of the library. 

That said there might be room here for some slightly better logic than utilising Socket.OSSupportsIPv6, as it seems (at least in my case) to be an unreliable flag.

I would suggest something like:

```
bool useIPv6 = Socket.OSSupportsIPv6 
                             && Dns.GetHostAddresses(host)
                                 .Where(x => x.AddressFamily == AddressFamily.InterNetworkV6).Any()
```

The basic idea being, If when I attempt to resolve the IP addresses for the given host name, there is an IPv6 address given, then attempt to use it. If there are no IPv6 addresses resolved, then we should not try to use IPv6, because its not properly supported.

That said there maybe a few scenarios where this could fall down (if the host OS only supports IPv6, but you only resolve to IPv4 addresses, then this will fail. So maybe add a check that if we only support IPv6, but only resolve IPv4 addresses, then map the addresses to IPv6)
