### ISSUE TITLE
Request-Reply with QueueingBasicConsumer is very slow in 3.6.5

### ISSUE THREAD

**Issue by tr00Hlodvig** [rabbitmq/rabbitmq-dotnet-client#284]
We use Req-Reply pattern with that consumer just because we need it and there is no other simple solution with rmq for that. So far worked ok, but after upgrade to 3.6.5 making request became very slow - we have to wait up to 40s for request completion. After downgrade to 3.5.4 requests returned to be fast.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
I'm sorry but we cannot suggest anything with this much information provided. Please post your question to the mailing list and consider profiling your consumer and taking a traffic dump in order to gather some data that might explain what's going on. I'd like to add that `QueueingBasicConsumer` is deprecated and recommended against in modern versions, and that more recent (`4.x`) releases of the client are available, including substantial consumer dispatch lock contention improvements.
