### ISSUE TITLE
RabbitMQ `channel.BasicPublish` to nonexistent queue "fails" silently

### ISSUE THREAD

**Issue by CGreenburg** [rabbitmq/rabbitmq-dotnet-client#298]
Today I learned that sending messages to a queue that doesn't exist will not throw an exception or anything. For example, if a change to an app.config queue name property was committed to master by chance, then queue messages would be thrown into space and we'd lose messages without knowing about it.

Is this the intended behavior? Are we expected to manually check if the queue exists by doing channel.QueueDeclarePassive at application startup? Seems like a background check in the library itself would be optimal.

I'm using v3.5.4 of RabbitMQ server and .NET library.

**Comment by bording** [comment]
If you need to know if a message was delivered, you should set the `mandatory` option on `BasicPublish` to true and then register an event handler on the `IModel.BasicReturn` event. The handler will be called for each undelivered message.

BTW, I know that the maintainers of this repo prefer questions be asked on their rabbitmq-users Google Groups mailing list, or on Stack Overflow, and not to use issues here for questions.

**Comment by michaelklishin** [comment]
It does not fail silently.

First of all, messages are not sent to queues, they are sent to exchanges. Publishing to a non-existent exchange is a channel exception in the protocol, which closes the channel and is clearly visible. It happens entirely asynchronously (there is no response for `basic.publish` in the protocol).

From there, if the exchange does exist, messages can be routed to zero or more queues. What happens if they are not routed is [answered in this recent rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/alternative$20exchange%7Csort:date/rabbitmq-users/Xl8el2929M8/G3Fja_8wCAAJ).

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
Your example with publishes "directly" to queues via the default exchange falls into the "unroutable messages" category.

**Comment by CGreenburg** [comment]
I appreciate the help!

Apologies for posting here; I should've done more research into the matter.
