### ISSUE TITLE
Threading problems with ConnectionFactory in ASP.NET application

### ISSUE THREAD

**Issue by smarts** [rabbitmq/rabbitmq-dotnet-client#299]
If someone writes a web app using ASP.NET then the threading & task model used by `ConnectionFactory` could have problems. ASP.NET has its own way of running work in the background (i.e., [HostingEnvironment.QueueBackgroundWorkItem()](https://msdn.microsoft.com/en-us/library/system.web.hosting.hostingenvironment.queuebackgroundworkitem(v=vs.110).aspx)) and it is incompatible with the TPL (Task Parallel Library).

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. This is a speculation and any possible solution needs a community-wide discussion first, so this is mailing list material. Thank you.

**Comment by smarts** [comment]
This isn't a question or speculation.

**Comment by michaelklishin** [comment]
Yes it is: It provides no specifics therefore cannot be addressed or even meaningfully discussed.

**Comment by michaelklishin** [comment]
You can consider it whatever you want: a bug report, a feature request, anything. But unless there are *specific examples of what cannot be done in ASP.NET and why*, this issue will remain closed because there is no way we can address something that's not well defined.

Surely there's more than one person who uses this client with ASP.NET. If this is an actual problem it will be reported again and again, one day with specific examples.

**Comment by smarts** [comment]
Now we've gotten to the real issue. You should use the same specificity you desire when you're addressing others. An issue being speculation isn't the same as it lacking the information that you desire before you attempt to address it. This probably still isn't specific enough, but here's at least a snippet that explains why it is desirable to use the function I noted:

From [here](https://blogs.msdn.microsoft.com/webdev/2014/06/04/queuebackgroundworkitem-to-reliably-schedule-and-run-background-processes-in-asp-net/)
> QBWI schedules a task which can run in the background, independent of any request. This differs from a normal ThreadPool work item in that ASP.NET automatically keeps track of how many work items registered through this API are currently running, and the ASP.NET runtime will try to delay AppDomain shutdown until these work items have finished executing.

**Comment by michaelklishin** [comment]
@smarts thank you for sharing some of your sarcasm to a small team of maintainers who get dozens of "it doesn't work [end of message]" every single day. Surely the only reason why we ask for details is because we want to feel superior to the reporter and not because we want to save ourselves some time. 

The amount of information you provided is barely enough for us to begin researching the issue. We still don't know squat about your environment, software versions used, what your code looks like, what issues you encountered, how they can be reproduced.
We also don't need any details on why you believe that what's covered in the article applies to this client: many Web apps *publish* messages but do not embed consumers ("regular" .NET apps do).

But we don't have to know any of that because we are so awesome that we can read your mind.

**Comment by michaelklishin** [comment]
I'm closing this issue because @smarts is more interested in questioning how we use GitHub issues than explaining what the problem is, why it is a problem, how it can be reproduced, and debating possible solutions. In case someone else hits the same problem, finds this issue and decides to be less of a [typical open source consumer](https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d), you know what to do: start a [rabbitmq-users thread](http://groups.google.com/group/rabbitmq-users) and provide as much information as possible because it is in everyone's interest: it leads to issues being resolved quicker, or at all.
