### ISSUE TITLE
Problem with AutorecoveringConnection

### ISSUE THREAD

**Issue by MIVerTFT** [rabbitmq/rabbitmq-dotnet-client#313]
I have some problem with auto reconnect. When my program lost connection with rabbit node, I call Dispose method on IConnection. It gone be all right, but I see the recovery thread still alive, and if node started again, recovery thread recur connection. Is this behavior correct? After all, if I have already lost the link to IConnection, it will remain hanging forever.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.
