### ISSUE TITLE
Is there a way now to pop message for specified timeout?

### ISSUE THREAD

**Issue by eocron** [rabbitmq/rabbitmq-dotnet-client#323]
Im trying to use RabbitMQ to try pop message for specified timeout. I found an answer that describe solution like this:

        private BasicDeliverEventArgs WaitForMessageWithTimeout(string queueName, int timeoutMs)
        {
            var consumer = new QueueingBasicConsumer(_model);
            var tag = _model.BasicConsume(queueName, true, null, consumer);
            try
            {
                BasicDeliverEventArgs result;
                if (!consumer.Queue.Dequeue(timeoutMs, out result))
                    throw new ApplicationException(string.Format("Timeout ({0} seconds) expired while waiting for an MQ response.", timeoutMs / 1000.0));

                return result;
            }
            finally
            {
                _model.BasicCancel(tag);
            }
        }

But QueueingBasicConsumer is depricated. How one should do this now?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
It'd probably be easier to use `IModel#BasicGet` which fetches a single message (much like HTTP GET).

**Comment by eocron** [comment]
Thank you for your answer, but is there a way to use more efficient approach through EventBasicConsumer logic?

**Comment by michaelklishin** [comment]
@eocron this is not a support venue, please ask questions on rabbitmq-users in the future.

You can cancel a consumer after a timeout with `IModel#BasicCancel`. Since it takes time for that frame to reach the server and be handled, there is a natural race condition between consumer cancellation and "in flight" deliveries. What that means is that you are not guaranteed to not get any more deliveries after you cancel, and therefore your consumer either needs to be prepared to handle that (e.g. requeue such late deliveries) or you need to use a lower timeout value than actually desired.
