### ISSUE TITLE
ConnectionFactory doesn't release socket on exception in CreateConnection

### ISSUE THREAD

**Issue by lomomike** [rabbitmq/rabbitmq-dotnet-client#337]
RabbitMq client doesn't release socket in Linux in case when RabbitMq is unreachable. 

My service opens Http endpoint and tries to connect to RabbitMq. **ConnectionFactory.CreateConnection** throws **BrokerUnreachableException** and my program retries to connect to RabbitMq after some time. Since RabbitMq does not exists on the machine (it is a valid case for my service) my application can exceed Linux limitation on sockets and it leads to impossibility to establish http connection with my service.

Linux version: Ubuntu 16.04.1 LTS
dotnet core version: 1.0.4
rabbitmq-dotnet-client version: 4.1.3

Example (without http endpoint): [Gist](https://gist.github.com/lomomike/f21de9a3f47810331a9f83deb1cfbdae)

Run result:
```
PID = 5476
Press any key to exit
[3] Cannot connect to RabbitMq
[4] Cannot connect to RabbitMq
[3] Cannot connect to RabbitMq
[4] Cannot connect to RabbitMq
[3] Cannot connect to RabbitMq
[4] Cannot connect to RabbitMq.
...
```
In second terminal:
```
lomomike@lomomike-pc:~$ sudo lsof -p 5476  | grep sock | wc -l
207
lomomike@lomomike-pc:~$ sudo lsof -p 5476 | grep sock | wc -l
239
lomomike@lomomike-pc:~$ sudo lsof -p 5476 | grep sock | wc -l
271
lomomike@lomomike-pc:~$ sudo lsof -p 5476 | grep sock | wc -l
464
lomomike@lomomike-pc:~$ sudo lsof -p 5476 | grep sock | wc -l
476
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Your code calls `factory.CreateConnection()` in a tight loop. I'm afraid that's not enough evidence that sockets are not released because new ones can be opened quicker than earlier ones are reclaimed, which is not necessarily immediate. I spotted no specific `waitingTimeout` value to reason about. 

Feel free to start a rabbitmq-users thread with an example that uses a delay of, say, 15-30 seconds.

**Comment by michaelklishin** [comment]
After a quick [SocketFrameHandler](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/4.x/projects/client/RabbitMQ.Client/src/client/impl/SocketFrameHandler.cs#L65) inspection with @kjnilsson we concluded that this is indeed an issue in the library.

Thanks for reporting, @lomomike.

**Comment by michaelklishin** [comment]
We decided to include this into `5.0` only because it's approaching GA and the `4.x` branch does not support most recent .NET Core build toolchain.

**Comment by lomomike** [comment]
@michaelklishin, thanks a lot.

**Comment by michaelklishin** [comment]
@lomomike any chance you can give #338 a try?

**Comment by lomomike** [comment]
@michaelklishin nice, PR looks good. Thanks!

**Comment by lomomike** [comment]
@michaelklishin I have build branch `rabbitmq-dotnet-client-337` and checked it with my example. Works like a charm, no leaked sockets. Thanks!

**Comment by michaelklishin** [comment]
@lomomike thanks for confirming! We will produce a new (hopefully the last) RC of `5.0.1` later today.
