### ISSUE TITLE
TLS peer verification is disabled by default

### ISSUE THREAD

**Issue by mbettex** [rabbitmq/rabbitmq-dotnet-client#339]
When connecting to a rabbitMq instance with the AMQPS protocol, the hostname is not checked against the common name of the SSL certificate.

The following code will happily connect to a rabbitMq server that has an SSL certificate with a common name that doesn't match its hostname.

```
var connectionFactory = new ConnectionFactory()
{
    Uri = "amqps://user:password@hostname/vhost"
};

using (var connection = connectionFactory.CreateConnection())
{
    Console.WriteLine("isOpen: {0}", connection.IsOpen);
}
```

I found out that we can opt in to this check by changing the AcceptablePolicyErrors. The following code will report an error when connecting to a rabbitMq server that has an SSL certificate with a common name that doesn't match its hostname.

```
var connectionFactory = new ConnectionFactory()
{
    Uri = "amqps://user:password@hostname/vhost"
};

connectionFactory.Ssl.AcceptablePolicyErrors = SslPolicyErrors.None;

using (var connection = connectionFactory.CreateConnection())
{
    Console.WriteLine("isOpen: {0}", connection.IsOpen);
}
```

I'm reporting this issue here because for me, it was totally unexpected that the behavior of the library was not secure by default, and I believe I'm not the only one in this case. Especially I could not find this pointed out anywhere in the documentation. As a matter of fact, this [page ](https://www.rabbitmq.com/ssl.html) says exactly the opposite.

> On the .NET platform, by default the hostname of the server you're connecting to needs to match the CN (Common Name) field on the server's certificate, otherwise the certificate will be rejected.

Would you consider changing this behavior to be secure by default, or at least point this out explicitly in the documentation?

**Comment by michaelklishin** [comment]
I see the following in the docs:

```
SslOptions.CertificateValidationCallback can be used to provide a RemoteCertificateValidationCallback delegate. The delegate will be used to verify peer (RabbitMQ node) identity using whatever logic fits the application. If this is not specified, the default callback will be used in conjunction with the AcceptablePolicyErrors property to determine if the remote server certificate is valid.
```

which suggests the client uses all defaults. What section led you to believe peer verification is enabled by default?

**Comment by michaelklishin** [comment]
While we are not against enabling peer verification by default, unfortunately, it's a double edged sword. It does improve protection against man-in-the-middle attacks but it's a complete disaster for beginners who don't understand it and barely can set up TLS at all.

We face the same dilemma with every client and so far we hear from users confused by TLS every day and from those who would like to see peer verification enabled by default once every couple of months. Sorry but the ratio makes it quite difficult to switch the default as our small team is already stretched thin with questions and support.

Bunny logs a warning when peer verification is not enabled saying it should be enabled in production.
IIRC Java client in master now does the same.

That doesn't mean we can't improve the docs (and [you can help](https://github.com/rabbitmq/rabbitmq-website/tree/live)), mention peer verification in the Production Checklist guide and reconsider this again. But for now, the default will stay the same. It's not because we don't care about security but because we are multiple orders of magnitude smaller than the user base and TLS-related questions take a non-trivial amount of time already.

**Comment by michaelklishin** [comment]
I updated the docs, will mention TLS in the Production Checklist guide next. @mbettex we'd welcome a pull request that logs a warning when peer verification is disabled.

**Comment by mbettex** [comment]
There is nothing in the documentation that made me think that peer verification was supposed to be enabled by default. That was only an assumption on my side based on the fact that security by default is usually the behavior that I saw in general when it comes to SSL.

I understand that in we have to choose the balance between having things easier or more secure. My opinion goes strongly in favor of the security side, but in the end it's your call to choose the balance for this project.

I also understand that you are a small team and that you have already probably a lot on your plate. I actually have the same problem and that's why I probably won't have the time to make that pull request that you suggest :-(

Anyway, thanks a lot for taking the time to review this issue and for updating the documentation, it's appreciated :-)

**Comment by lukebakken** [comment]
Feel free to use [this validation callback](https://github.com/basho/riak-dotnet-client/blob/develop/src/RiakClient/Auth/RiakSecurityManager.cs#L100-L158). I wrote it to ensure that the server cert presented by Riak has a `CN=` value matching the server's DNS name.
