### ISSUE TITLE
IModel.BasicCancel cann't cannel the consumer receive event

### ISSUE THREAD

**Issue by liurongwei** [rabbitmq/rabbitmq-dotnet-client#340]
`ConnectionFactory factory = new ConnectionFactory();
            factory.Uri = new Uri(bootstrapServers);
            IConnection conn = factory.CreateConnection($"benchmark/produce/{TestUtil.GetLocalIPAddress()}");

            Console.WriteLine($"test:{nTests} queue:{queueName} messages:{nMessages} ");

            var startTime = DateTime.Now.Ticks;
            var model = conn.CreateModel();
            conn.AutoClose = true;

            AutoResetEvent resetEvent = new AutoResetEvent(false);

            var consumer = new EventingBasicConsumer(model);
            var consumerTag = string.Empty;
            consumer.Received += (ch, ea) =>
            {
                if (count >= nMessages)
                {
                    var duration = DateTime.Now.Ticks - startTime;
                    Console.WriteLine($"total {count},{count / (duration / 10000.0):F0} messages/ms");
                    resetEvent.Set();
                    return;
                }

                var body = ea.Body;

                var msg = Encoding.UTF8.GetString(body);
                Console.WriteLine(string.Format("read message : {0}", msg));

                // ... process the message
                model.BasicAck(ea.DeliveryTag, false);
                count++;
            };
            consumerTag = model.BasicConsume(queueName, false, consumer);
            resetEvent.WaitOne();
            model.BasicCancel(consumerTag);
            model.Close();`

I have tried some method the cancel consume event after receive a number of (1000) message , and called the model.BasicCancel(consumerTag) method and close the model , but the consumer.Received event still fired, 

How to cancel the consumer in a application safely ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Cancelling a consumer cannot cancel messages that are "in flight". Closing a channel can't either because `basic.cancel` takes time to reach the server and be processed. Use [prefetch](http://www.rabbitmq.com/confirms.html) to limit the number of outstanding deliveries. A flag in your code that tells the consumer ignore or requeue (if you close the channel, explicitly requeueing isn't necessary) deliveries that arrive after.
