### ISSUE TITLE
Messages lost on exchange

### ISSUE THREAD

**Issue by serbancosmincst** [rabbitmq/rabbitmq-dotnet-client#342]
Hello,
I have been testing the .NET client for a couple of days now and i came across a strange behaviour. I have a durable Exchange that has some durable queues on a cluster of 2 nodes. The queues use the policy to mirror accros all nodes in the cluster and also sync autmatically ( also lazy queues if it is relevant) . I am publishing messages to that exchange in persistent mode and also pass all the nodes on the cluster to the connection so it can reconect automatically in case one of the nodes dies. The strange part comes when i disconnect on purpose the node on which a producer publishes messages. There is a a short period of time ( approximately 10-15 seconds) between the Connection Shutdown event and the Recovery Succeded event where the said producer still publishes message to the exchange as if nothing has happened and i can't seem to be able to recover those messages. I must also mention that i use confirms on producer aswell.
Thanks.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Automatic connection recovery in this client does not internally [meaning in the client] enqueue messages that were published while a connection was down. That's a responsibility of application developer on top of publisher confirms. While we'd be interested in adding this feature to connection recovery, it can result in duplicates and therefore is not always a safe thing to do.

**Comment by OlegStotsky** [comment]
@michaelklishin I'm experiencing the same problem and as OP mentioned I use publisher confirms and get confirmations for all the lost messages. Not sure what is the responsibility of application developer in that case?

**Comment by lukebakken** [comment]
@OlegStotsky - if you are going to make multiple comments in different repositories, at least make it possible for us to assist you.

Please carefully read my comment [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions/1284#discussioncomment-8606877) and follow my instructions if you would like assistance.

**Comment by michaelklishin** [comment]
@OlegStotsky do you seriously expect to get help by commenting on a seven year old issue without any details?
