### ISSUE TITLE
Unable to find Model and Constants classes while source code surfing

### ISSUE THREAD

**Issue by yar1k0v** [rabbitmq/rabbitmq-dotnet-client#345]
My question might be very inappropriate and simple, but I have to ask it anyway, cause I wasn't able to find an answer by myself.

I've downloaded the latest version of master branch and started to investigate the source code. I need to understand how the library work to avoid mistakes while the development. 

at some point of my investigation, I've found out that there are two classes are missing in the repository - Model and Constants. I've checked multiple times files in different branches, but without any success.

Did I miss something or those classes don't even exist or were excluded from the repo?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
They are [generated from a protocol spec document](https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/master/projects/client/Apigen).

**Comment by yar1k0v** [comment]
Ok, thank you for the answer.
