### ISSUE TITLE
multi connections with a queue some connection stuck on the ack.

### ISSUE THREAD

**Issue by liurongwei** [rabbitmq/rabbitmq-dotnet-client#346]
client vrsion 5.0.1

i have create 40 connection with a queue named "Feeds.ActiveUser ", but there are still a few connection stuck on the ack (use manual ack method ),   stuck amounts are not always same .

Overview | Messages | Message rates | +/- -- | -- | -- | --
/ | Feeds.ActiveUser | m-redis-1 +4 | D ha-all | running | 0 | 13 | 13 | 0.00/s | 0.00/s | 0.00/s

Channel | Consumer tag | Ack required | Exclusive | Prefetch count | Arguments
-- | -- | -- | -- | -- | --
172.17.5.234:58730 (1) | amq.ctag-8qNHztp8372sZsj10HfJ0g | ● | ○ | 1 |  
172.17.5.234:58889 (1) | amq.ctag-18djovmKu28WNJ6SGdCsAQ | ● | ○ | 1 |  
172.17.5.234:58892 (1) | amq.ctag-vaO7BwDKL86dzm-yf1SOGg | ● | ○ | 1 |  
172.17.5.234:58858 (1) | amq.ctag-4_0T6sGuIeqzRx--LW2zvQ | ● | ○ | 1 |  
172.17.5.234:58857 (1) | amq.ctag-1Q6fBb-fp1dS8s-BzeI5Ag | ● | ○ | 1 |  
172.17.5.234:58736 (1) | amq.ctag-aP6xnP_zxQa6FaeobR9SEw | ● | ○ | 1 |  
172.17.5.234:58826 (1) | amq.ctag-yavEGVZlgxLOFlpp_CVVjA | ● | ○ | 1 |  
172.17.5.234:58746 (1) | amq.ctag-0PnIT6Fw6Ec9KpnCixonqg | ● | ○ | 1 |  
172.17.5.234:58888 (1) | amq.ctag-TVjCho8CAG03TsjF6ospuw | ● | ○ | 1 |  
172.17.5.234:58728 (1) | amq.ctag-KFzB63EG3mADLwNL8djuRQ | ● | ○ | 1 |  
172.17.5.234:58887 (1) | amq.ctag-tkbDpw23--tYSQLkkyPA1g | ● | ○ | 1 |  
172.17.5.234:58732 (1) | amq.ctag-Lw6oz5W2MTg796bTajyI9Q | ● | ○ | 1 |  
172.17.5.234:58893 (1) | amq.ctag-tB6hjaDAjZ_OBLJR2vJ0dg | ● | ○ | 1 |  
172.17.5.234:58737 (1) | amq.ctag-LQrl_U46mgNVFTaseAZbbw | ● | ○ | 1 |  
172.17.5.234:58745 (1) | amq.ctag-XPbwN5E-Qyi_ulWSRqwtYA | ● | ○ | 1 |  
172.17.5.234:58885 (1) | amq.ctag-LZ6vw6rNStDS2hMJjkM3nQ | ● | ○ | 1 |  
172.17.5.234:58729 (1) | amq.ctag-e0OpLj3UgBekap6DDvLO6A | ● | ○ | 1 |  
172.17.5.234:58738 (1) | amq.ctag-7ZtwR2BavzVMI5ZTX807DQ | ● | ○ | 1 |  
172.17.5.234:58741 (1) | amq.ctag-bXCi3VFz7AdC73JHFA1_iA | ● | ○ | 1 |  
172.17.5.234:58742 (1) | amq.ctag-c3MqwAiOuULYLIODnIMLFg | ● | ○ | 1 |  
172.17.5.234:58743 (1) | amq.ctag-5ocxzg98RyPJYoIqR0KZww | ● | ○ | 1 |  
172.17.5.234:58731 (1) | amq.ctag-PcHyPqX0AEYihh7havhMSA | ● | ○ | 1 |  
172.17.5.234:58748 (1) | amq.ctag-irfrvlGAF41ijbQZbTlbzQ | ● | ○ | 1 |  
172.17.5.234:58739 (1) | amq.ctag-sXZiuKxdIdwtcvbG-r5sZA | ● | ○ | 1 |  
172.17.5.234:58734 (1) | amq.ctag-q8DjMMftf7wU4iCGF63PCw | ● | ○ | 1 |  
172.17.5.234:58763 (1) | amq.ctag-sJ96qyQzI6_Z6HwGjaqhUQ | ● | ○ | 1 |  
172.17.5.234:58841 (1) | amq.ctag-3IaVGs1MSbVPHzZvfO89XA | ● | ○ | 1 |  
172.17.5.234:58886 (1) | amq.ctag-LiaxJw5ARPhuOYHrFi6png | ● | ○ | 1 |  
172.17.5.234:58891 (1) | amq.ctag-OeRXlEqqu-uve5A3Eo4QLA | ● | ○ | 1 |  
172.17.5.234:58818 (1) | amq.ctag-atnHPN7oq9QcbOdq4PR1Sg | ● | ○ | 1 |  
172.17.5.234:58895 (1) | amq.ctag-elmPtKX92To6ojCy3KzL3g | ● | ○ | 1 |  
172.17.5.234:58733 (1) | amq.ctag-M5oc4eQC9okbaOF4PI7SsA | ● | ○ | 1 |  
172.17.5.234:58764 (1) | amq.ctag-XUF68Lr7luVMyF31TDcWuQ | ● | ○ | 1 |  
172.17.5.234:58744 (1) | amq.ctag-3-avxBZHNvhqKw9KXy67Lg | ● | ○ | 1 |  
172.17.5.234:58777 (1) | amq.ctag-OSEfxBfZDxzE65dou1Dtsg | ● | ○ | 1 |  
172.17.5.234:58899 (1) | amq.ctag-yt6raSKS5ReaB_-U_Gd7yw | ● | ○ | 1 |  
172.17.5.234:58762 (1) | amq.ctag-VAbXrqr9m-HON1z1L-Meeg | ● | ○ | 1 |  
172.17.5.234:58884 (1) | amq.ctag-w1qBLtA5ZnxrlqZfpHJFXQ | ● | ○ | 1 |  
172.17.5.234:58740 (1) | amq.ctag-2WIDuIQCdXgDx1w8DzbI1A | ● | ○ | 1 |  
172.17.5.234:58890 (1) | amq.ctag-CDnHJhq7zgMGXDyTUBejHg | ● | ○ | 1 |  

there are 13 connection cann't continue to consume message , and they were stucked on ack process.

**Comment by liurongwei** [comment]
![all connection](https://user-images.githubusercontent.com/1342352/30002166-17e07d4a-90d5-11e7-9ec2-8e764888a2cd.png)
![stuck connections](https://user-images.githubusercontent.com/1342352/30002168-1bd46268-90d5-11e7-9528-389301496937.png)

this the snapshot

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
There is no evidence that this is a client library issue. Consumers in your code can fail to acknowledge messages or take longer than usual. This is mailing list material.
