### ISSUE TITLE
Topology recovery does not recover queue binding

### ISSUE THREAD

**Issue by Flohack74** [rabbitmq/rabbitmq-dotnet-client#347]
Hi,

suppose the following setup:

```
connectionFactory.UserName = userName;
connectionFactory.Password = password;
connectionFactory.HostName = hostName;
connectionFactory.VirtualHost = virtualHost;
connectionFactory.AutomaticRecoveryEnabled = true;
connectionFactory.NetworkRecoveryInterval = TimeSpan.FromSeconds(reconnectHeartbeat);
connectionFactory.RequestedHeartbeat = reconnectHeartbeat;

connection= connectionFactory.CreateConnection();
connection.ConnectionRecoveryError += onConnectionRecoveryError;
connection.RecoverySucceeded += onConnectionRecoverySucceeded;

channel = connection.CreateModel();
channel.ExchangeDeclare(exchangeName, ExchangeType.Fanout, false, true);
channel.QueueDeclare("", false, true, true, options);
channel.QueueBind("", queueName + "_Event", "", null);
```

So multiple clients bind with a nun-durable anonymous queue to a non-durable event exchange, and in the case of a connection loss I would expect that with automatic recovery they also get reconnected to the exchange.

This does not seem to be the case, the queues are re-created, but not the binding to the exchange.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Queue name will be different after recovery by design. Java and .NET clients try to keep track of the topology reasonably intelligently and recovery has a [decent test suite](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/Unit/src/unit/TestConnectionRecovery.cs).

`channel.QueueBind` with an empty queue name is not supported by connection recovery. I'm not sure what the intent is but there's an obscure and extremely rarely used AMQP 0-9-1 feature that IIRC means "bind to the most recently declared queue". Clients are not aware of that since this is a piece of state that only the server has. There are no plans to support this obscure feature in connection recovery.

Use queue name that is returned by `IModel#QueueDeclare` or a client-provided queue name and recovery will work like a charm.

**Comment by Flohack74** [comment]
Ok I partly understand this, but what is not clear to me, even if the queue name is empty/randomized/dynamic and the server does not track this, the client knows that before this queue was bound to an exchange, and during recovery, should be rebound. Or is queue bind operation not remembered on the client at all?

**Comment by Flohack74** [comment]
Ok after investigating this further its clear that we should not do
```
channel.QueueBind("", queueName + "_Event", "", null);

with empty queue name, I picked up your suggestion now. It works perfectly thx

**Comment by michaelklishin** [comment]
@Flohack74 the server does "track" queue names and so does connection recovery but recovery does not try to determine what queue was the most recently declared, so queue name is taken literally to be an empty string, which means it then attempts to bind a queue that cannot possible exist.
