### ISSUE TITLE
How to handle downtime for windows service and rabbitmq

### ISSUE THREAD

**Issue by priyankaaravind** [rabbitmq/rabbitmq-dotnet-client#353]
I have windows service to process my request asynchronously. 
While i started service for 1st time it processes all the requests from rabbitMQ queue.
At some time service not processed the queue of requests even though in running state. (It happens while trying to access rabbitmq after 1 day)
If i restart again it will process the queue.
Is this should be consider as rabbitmq downtime or service downtime.
How to get notification for this downtime of rabbitmq as well as for windows service.

`string queueName = "queuename";

                // Set up the RabbitMQ connection and channel
                var connectionFactory = new ConnectionFactory
                {
                    //ServerUri is nothing but rabbitmq url 
                    Uri = ConfigurationManager.AppSettings["ServerUri"].ToString(),
                    Protocol = Protocols.AMQP_0_9_1,
                    RequestedFrameMax = UInt32.MaxValue,
                    RequestedHeartbeat = UInt16.MaxValue
                };

                using (var connection = connectionFactory.CreateConnection())
                using (var channel = connection.CreateModel())
                {
                    // This instructs the channel not to prefetch more than one message
                    channel.BasicQos(0, 1, false);

                    // Create a new, durable queue
                    channel.QueueDeclare(queueName, true, false, false, null);

                    using (Subscription subscription = new Subscription(channel, queueName, false))
                    {
                        UTF8Encoding encoding = new UTF8Encoding();
                        while (channel.IsOpen)
                        {
                            BasicDeliverEventArgs eventArgs;
                            bool success = subscription.Next(2000, out eventArgs);
                            if (success == false) continue;
                            byte[] msgBytes = eventArgs.Body;
                            string message = encoding.GetString(msgBytes);
                            ClusterFormation.ProcessCluster(message);
                            channel.BasicAck(eventArgs.DeliveryTag, false);
                        }
                    }
                }`

In this while starting service for first time everything works fine. But if we leave service free for 1 day it jut hangs. subscription.Next always return false.
Please help me to resolve this.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
See server and Windows logs for clues.Management UI, for example, for how many [unacknowledged deliveries there can be](http://www.rabbitmq.com/confirms.html).

Add logging to your apps, for example, any unhandled exceptions in consumer handlers or anything else that can prevent consumers from processing deliveries or acknowledging them.

If RabbitMQ node fails all client connections will be closed and (assuming connection recovery is enabled) will try to recover, which are logged.

**Comment by michaelklishin** [comment]
Ah, our old friend `Subscription.Next` is referenced in the very last line. It does not support [automatic connection recovery](http://www.rabbitmq.com/dotnet-api-guide.html) so I highly recommend avoiding it. Use any other consumer implementation, e.g. `EventingConsumer` or subclass `DefaultBasicConsumer`.

Client connection loss is easy to spot in server logs and sometimes in the management UI.
