### ISSUE TITLE
NET Standard 2.0 (.NET Core 2.0) support

### ISSUE THREAD

**Issue by CodingHarry** [rabbitmq/rabbitmq-dotnet-client#355]
For now our server side application is based on the asp.net core 1.1 framework. We use RabbitMQ for micro service communication. Next days we will upgrade to asp.net core 2.0 to be able to use SignalR for realtime Client <-> Server communication. 

netcore2.0 targets do not support dependencies lower than netstandard 2.0

**Comment by adamralph** [comment]
All the .NET Standard versions from 1.0 to 2.0 are backwards compatible. I.e. any platform which implements a given version .NET Standard in that range, also implements every version of .NET Standard prior to that version.

Since .NET Core 2.0 implements .NET Standard 2.0, it also implements every version of .NET Standard back to 1.0.

The RabbitMQ client should continue to target the lowest version of .NET Standard possible, in order to maximise the number of platforms it is usable with, including .NET Core 2.0.

**Comment by michaelklishin** [comment]
@CodingHarry what specifically would you like to see changed?

**Comment by adamralph** [comment]
Or to put my point more simply: the client already supports .NET Standard 2.0 and .NET Core 2.0 (because it supports .NET Standard 1.5).

(Unless there's something very unusual going on, but I can't spot anything.)

**Comment by michaelklishin** [comment]
I trust @adamralph's judgement :)

**Comment by CodingHarry** [comment]
@adamralph, @michaelklishin,

Our issue is how we are depending on raabitmq. RabbitMq is referenced by a .net library project. This library project is referenced by the asp .net core 2 project within the same solution (VS2017 Upd3). No compile errors but i got an exception thrown "System.FileNotFoundException: Can not find rabbitmq.client...." during runtime.

¯\_(ツ)_/¯

After i added the same rabbitmq nuget reference to asp.net core 2 application runtime is able to load dll as expected.

Before that me and my team where thinking netcoreapp2.0 targets would not be able to reference netstandard versions lower than 2.0

It was certainly an issue on my missing knowledge :( so sorry for my mistake to put an issue here :( 

THX for your replies!
