### ISSUE TITLE
Expose channels/models objects cached in connection object

### ISSUE THREAD

**Issue by dickens-code** [rabbitmq/rabbitmq-dotnet-client#358]
Hi, is that possible to (simply) expose ALL cached channels (ie. models) inside connection object? 

Our app would like to reuse both sender channels and receiver channels as much as possible. Right now we have to explicitly maintain them inside application code hash table which may lead to inconsistency to underlying caches.

Thanks a lot
Dickens.

**Comment by michaelklishin** [comment]
The "cached" channels are kept around for automatic connection recovery (if it's enabled). We have no plans to expose them because messing with them will trip up the recovery process. There are projects (at least in the Java world) that provide connection pooling over the "regular" RabbitMQ client. This works reasonably well and what we'd recommend.

**Comment by dickens-code** [comment]
I see, so is there any similar project around .net client?

**Comment by michaelklishin** [comment]
I don't think EasyNetQ implements pooling since it's pretty small. NServiceBus and MassTransit are more likely to offers connection pooling. And perhaps there are generic object pooling that's configurable enough to make them not offer channels on closed connections and/or open channels to replace those that run into channel-level exceptions.

**Comment by pardahlman** [comment]
Hello hi,

Just wanted to chime in and say that a client I'm maintaining, [RawRabbit](https://github.com/pardahlman/RawRabbit/), implements a [`ChannelFactory`](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/Channel/ChannelFactory.cs) that creates a pool of channels which are re-used in the application. It round-robins between the created channels and temporary removes closed channels that are recoverable from the pool and re-adds them when the channel is recovered. It even has some basic functions to increase/decrease the pool based on current workload. More information here: http://rawrabbit.readthedocs.io/en/master/inner-workings.html#channelfactory
