### ISSUE TITLE
AMQP Operation Interrupted

### ISSUE THREAD

**Issue by thyams** [rabbitmq/rabbitmq-dotnet-client#363]
![image](https://user-images.githubusercontent.com/1414138/31350199-48ae3d50-acf4-11e7-918b-68e4d9c006d4.png)

Using the latest NuGet .NET Client with AutoRecover on ConnectionFactory enabled. .NET Framework v4.6.2 and C# 7.0.

Actual constructor call:          
```
     m_connectionFactory = new ConnectionFactory();
     m_connectionFactory.AutomaticRecoveryEnabled = true;
     m_connectionFactory.TopologyRecoveryEnabled = true;
     m_connectionFactory.RequestedConnectionTimeout = 15000;
     m_connectionFactory.SocketReadTimeout = 10000;
     m_connectionFactory.SocketWriteTimeout = 10000;
     m_connectionFactory.Uri = new Uri( m_globalSettings.CloudRabbitConnectionString );

     VerifyConnection();
     m_logger.LogInformation( "QueueSyncService constructed." );
```

Noticed that we frequently get an issue where AMQP operation is interrupted in our audit logs.

Got some additional information from recording the exceptions recently.
![image](https://user-images.githubusercontent.com/1414138/31350241-72388de2-acf4-11e7-91a6-e6e97cc88f27.png)

I took a look at the code =>
`
        public ISession Lookup(int number)
        {
            lock (m_sessionMap)
            {
                return m_sessionMap[number];
            }
        }
`
(https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/SessionManager.cs - line 176)

I see we aren't checking internally (in the library) if Dictionary.ContainsKey() before using said Key. It's generally consider "proper" to check if key exists, much like OutOfIndex exceptions - I am not really here to judge.

While that might be used to return NULL if key doesn't exist, the problem here is that I have no manual control over whether Sessions exists or do not exists - that role/responsibility would be internal to the library. Therefore I feel that there is some error handling logic on when a session needs to be destroyed/disposed off, but it appears to not being removed from the SessionMap itself. The timestamps should indicate that these calls occurred at different times. Not a quick fire rapid succession of each other (i.e. shouldn't be some arbitrary race condition where calls were deadlock on the same variable lock).

This issue did not appear for us until I abandoned manually recreating connections when IsOpen returns false and trusted in the Library to handle re-connection of transient network issues.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Automatic connection recovery does [a limited number of things](http://www.rabbitmq.com/dotnet-api-guide.html) and there are at least two things it does not do (which is likely the root cause here, not how the channel map is checked for a key):

 * It will not recover from channel-level exceptions [as in the protocol, not C#], which do happen. It's your application's responsibility.
 * It will not enqueue any attempted publishes while connection is down. Doing so is something we've been considering but unless you get a write-ahead log for this feature right, your apps can begin running out of heap very quickly.

I have no details about what your apps do but when the above limitations are taken into account, automatic connection recovery works very well and has been for years.

**Comment by thyams** [comment]
We handle channel level exceptions but perhaps we did something wrong?

```
IModel channel = null;
try
{
    channel = m_connection.CreateModel();
}
catch( Exception ex )
{
    channel = null;
    m_logger.LogError( $"Failed to open channel. Message ({ex.Message}). StackTrace ({ex.StackTrace})" );
}

if( channel != null )
{
    // TODO: Can be multi-threaded.
    while( !m_mailbox.IsEmpty )
    {
        Letter letter = null;
        if( m_mailbox.TryDequeue( out letter ) )
        {
            if( !( await SendLetterToCloudAsync( channel, letter ) ) )
            {
                MarkForRetryOrAbandon( letter );
            }
        }
    }

    m_redeliveryCounter = new Dictionary<string, int>();
    success = true;

    // Close Channel - Don't Dispose
    if( !channel.IsClosed )
    {
        channel.Close( 200, "Goodbye!" );
    }
    // TODO: Move Redeliveraries to Mailbox
}
```

**Comment by michaelklishin** [comment]
@thyams you are not handling the kind of exceptions I'm referring to. See the table at the bottom of http://www.rabbitmq.com/amqp-0-9-1-reference.html. Try declaring a queue as durable and then under the same name as transient. Try double acking a delivery tag. Those protocol-level exceptions are sent asynchronously by the server and immediately close the channel (which is why the client will remove it from its channel map). Automatic connection recovery cannot know how to recover from them or whether it even should try. You must open a new channel.

Our team does not use GitHub issues for discussions, investigations, RCA and so on. Please take this to rabbitmq-users.
