### ISSUE TITLE
Question: What is the alternative to TunneledTcpClient

### ISSUE THREAD

**Issue by UncleFirefox** [rabbitmq/rabbitmq-dotnet-client#371]
Hello, after upgrading the library version I see that `TunneledTcpClient` no longer exists and to return a proper `ITcpClient` I just have `TcpClientAdapter`.

What would be the equivalent to this?
```
new TunneledTcpClient(addressFamily, _config.ProxyHost, _config.ProxyPort, _config.ProxyUsername, _config.ProxyPassword);
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by UncleFirefox** [comment]
Is it so hard to answer the question which is VERY SPECIFIC to the library? For traceability I posted this on groups: https://groups.google.com/forum/#!topic/rabbitmq-users/y4DICH2V7NY

**Comment by michaelklishin** [comment]
@UncleFirefox I don't have the time to explain why we do things this way. Our small team spends *a lot* of time on user support, every day, for free, and all we ask for in return is playing by our rules (which are not crazy and exist for a reason). If you can't be bothered to do that and think you are a special and must be treated differently from everyone else, just figure things out on your own.
