### ISSUE TITLE
there was an unhandle exception when rabbitmq broker shutdown with replycode 320

### ISSUE THREAD

**Issue by xianjin-xu** [rabbitmq/rabbitmq-dotnet-client#373]
Application: SE.DSP.Pop.Communication.ServiceHost.exe Framework Version:  v4.0.30319 Description: The process was terminated due to an unhandled  exception. Exception Info: System.IO.FileNotFoundException at  RabbitMQ.Client.ESLog.Error(System.String, System.Exception) at  RabbitMQ.Client.Framing.Impl.Connection.LogCloseError(System.String,  System.Exception) at RabbitMQ.Client.Framing.Impl.Connection.ClosingLoop() at  RabbitMQ.Client.Framing.Impl.Connection.MainLoop() at  System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at  System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) at  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) at  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object) at  System.Threading.ThreadHelper.ThreadStart()
--

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
> System.IO.FileNotFoundException at RabbitMQ.Client.ESLog.Error(System.String, System.Exception) at RabbitMQ.Client.Framing.Impl.Connection.LogCloseError(System.String, System.Exception)

suggests a log file does not exist. Logging in this client is opt-in, so how exactly you set that up is up to your application.

**Comment by xianjin-xu** [comment]
@michaelklishin  thank you very much for fast replay.
i just use ConnectionFactory to create a IConnection object, there was no properties or method to set the logging opt-in or log file path. i used third part component of Log4.net
other info message or error message all can be writed in the log files, but this is an unhandleexception at the sub thread in the rabbitmq.Client.dll
could you help to tell me where can i set the logging opt-in about rabbitmq.client.dll  when use connectionfactory and IConnection?

below is the log4.net configuration info:
<log4net>
    <appender name="RollingFile" type="log4net.Appender.RollingFileAppender">
      <file value="log\\"/>
      <appendToFile value="true"/>
      <rollingStyle value="Composite"/>
      <datePattern value="'Communication.'yyyyMMdd'.log'"/>
      <StaticLogFileName value="false"/>
      <CountDirection value="1"/>
      <maxSizeRollBackups value="-1"/>
      <maximumFileSize value="1MB"/>
      <Encoding value="UTF-8"/>
      <PreserveLogFileNameExtension value="true"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%d{yyyy-MM-dd HH:mm:ss.fff} %property{log4net:HostName} %thread %-5level %message%newline"/>
      </layout>
    </appender>
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="RollingFile"/>
    </root>
  </log4net>

**Comment by michaelklishin** [comment]
This is not a support forum.
