### ISSUE TITLE
KeyNotFoundException from main loop.

### ISSUE THREAD

**Issue by roinet** [rabbitmq/rabbitmq-dotnet-client#382]
Hello.

RabbitMQ.Client: 4.1.3
RabbitMQ broker: 3.6.9
.Net framework: 4.6.1
OS: Windows 10.0.16299

We receive exceptions, that initiated by Library, code=541, text="Unexpected Exception", classId=0, methodId=0, cause=System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RabbitMQ.Client.Impl.SessionManager.Lookup(Int32 number)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
This exception catch after RabbitMQ broker (version 3.6.9) restarting (initiated by manually).

What is it may be and what we must to do to fix this problem? May be we don't close something correctly?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much without seeing your code. When target RabbitMQ node is restarted, connection is expected to fail one way or another and it more often than not will result in an exception to be logged.

See [Connection Recovery docs](https://www.rabbitmq.com/dotnet-api-guide.html) in the .NET client guide.

**Comment by roinet** [comment]
I know about AutomaticRecoveryEnabled property and we used this options, but this does not work at some cases (if I remember correct, client did not restore topology at cluster environment) and we implement custom logic for reconnecting and recover topology. 
If we get KeyNotFoundException from main loop, may be this because we try to use channels (IModel) after connection closed?

**Comment by michaelklishin** [comment]
I cannot suggest much since I don't have your code, in particular recovery code, or any steps to reproduce.

The dictionary in question stores channels (.NET client has an unfortunate and non-standard naming pattern where channels are represented as `IModel`s in some places and `Sessions` internally). Any channel operation on a closed connection is expected to fail.

Consider using automatic connection recovery provided by the library.
