### ISSUE TITLE
How does the client Heartbeat work?

### ISSUE THREAD

**Issue by GSerjo** [rabbitmq/rabbitmq-dotnet-client#409]
Could you please clarify how does the client heartbeat work

As per the code below, thread constantly read in `MainLoopIteration`

```
        public void MainLoop()
        {
            try
            {
                bool shutdownCleanly = false;
                try
                {
                    while (m_running)
                    {
                        try
                        {
                            MainLoopIteration();
                        }
                        catch (SoftProtocolException spe)
                        {
                            QuiesceChannel(spe);
                        }
                    }
                    shutdownCleanly = true;
                }
                catch (EndOfStreamException eose)
                {
                etc
```
I'm wondering, why does the client read a frame without stopping? Is it ok? i.e. I did not find any `WaitHandle`/`sleep` which blocks the `main thread`
```
        public void MainLoopIteration()
        {
            InboundFrame frame = m_frameHandler.ReadFrame();

            NotifyHeartbeatListener();
            // We have received an actual frame.
            if (frame.IsHeartbeat())
            {
                // Ignore it: we've already just reset the heartbeat
                // latch.
                return;
            }
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
