### ISSUE TITLE
String headers are decoded as byte arrays

### ISSUE THREAD

**Issue by bharaba** [rabbitmq/rabbitmq-dotnet-client#415]
Before the properties make it through the bus, if you set a property "foo" to equal "bar" and then retrieve it, you will get the string "bar". After the properties make it through the bus and the message is delivered, retrieving "foo" returns a byte[] and not a string. The byte[] has to be decoded before use. Not fatal but annoying.

Code:
```c
public static T GetCustomProperty<T>(this IBasicProperties properties, string key)
        {
            ContractSlim.Requires<ArgumentNullException>(properties != null);

            if (properties.HasCustomProperty(key))
            {
                var value = properties.Headers[GetCustomPropertyKey(key)];
                if (typeof(T) == value.GetType())
                {
                    return (T)value;
                }

                string json;
                // HACK: We set this as a string, but deliveries will return a UTF8-encoded byte[].
                if (value.GetType() == typeof(byte[]))
                {
                    json = Encoding.UTF8.GetString((byte[])value);
                }
                else if (value is string)
                {
                    json = (string)value;
                }
                else
                {
                    throw new InvalidCastException($"{value.GetType()} is an unknown property value type");
                }

                return JsonConvert.DeserializeObject<T>(json);
            }
            return default(T);
        }
```

**Comment by michaelklishin** [comment]
The protocol isn't really aware of the difference between strings and byte arrays on the wire. Strings are automatically converted to byte arrays at the moment. Changing this is possible but will

 * Be a breaking change after about 10 years
 * Have to go into a new major release
 * Will be considered to be an annoyance by some

@kjnilsson @adamralph @danielmarbach @bording @lukebakken WDYT?

**Comment by lukebakken** [comment]
A note can be made of this inconsistency for the next major release. If anything I'm surprised we convert any values for users of the library.

**Comment by bording** [comment]
Given that RabbitMQ already has the idea of a [byte array field value type](https://github.com/bording/rabbitmq-dotnet-client/blob/55355a64f1e5d15f51c7af36789cc5dc96a28b82/projects/client/RabbitMQ.Client/src/client/impl/WireFormatting.cs#L154) that's an extension of the spec, if that distinction could have been leveraged,  then `System.String` could have been encoded/decoded on behalf of the user for the `S` field type, and raw byte arrays could be handled by `x`. This would also align the behavior with how `short-string` is handled, [since they are decoded back to strings when reading them](https://github.com/bording/rabbitmq-dotnet-client/blob/55355a64f1e5d15f51c7af36789cc5dc96a28b82/projects/client/RabbitMQ.Client/src/client/impl/WireFormatting.cs#L199).

However, changing that now doesn't really seem possible. The last thing I'd want to see happen here is a change that impacts the wire-compatibility between versions of the client.

It might make sense to make a change here that was opt-in, so if you're willing to take the break, you could, but I don't see how it could be the new default.

**Comment by bharaba** [comment]
Hello,

Thanks for the response. It's more of a consistency issue really. If it makes more sense then have the properties values accept byte[] not object and avoid confusion.

I'm basically saying if you set it to something you should expect the same type when you retrieve it.

**Comment by bharaba** [comment]
@bording the code above already addresses the inconsistency and once it's in, i doubt I'll ever revisit the code. Nevertheless, I figured I would point it out ;)

**Comment by lukebakken** [comment]
Do people have an opinion about this issue with regard to version `6.0` (which allows API changes)?

**Comment by michaelklishin** [comment]
I think we should do it in `6.0`.

**Comment by bording** [comment]
What exactly would be changed? The concern I have is can this be done in a way that doesn't break compatibility between versions?

**Comment by michaelklishin** [comment]
@bording string header values that were serialised as a byte array would show up as strings if we make the change. It makes semantic sense but yes, would be breaking for some. I don't see a way to make this backwards compatible.

**Comment by michaelklishin** [comment]
I am not all sold on the change, that's just my opinion. If we decide to do it at all (again, I think it makes total sense semantically), now is the time.

**Comment by bording** [comment]
How would would it be distinguishing between strings and actual byte arrays? Last time I looked into this, I didn't see a way to make that distinction since they are handled the same way right now.

If a 6.0 client loses the ability to talk to older clients properly, then I don't think this is safe change to make. It's not reasonable to expect that all client usage be upgraded all at once.

**Comment by michaelklishin** [comment]
There isn't one because a byte array is not a data type in AMQP 0-9-1. Most users work with strings, not byte arrays.

There will be no changes to how strings are serialized, only to how byte arrays are deserialized.

**Comment by bording** [comment]
Right now it is possible to have the following code:

```
var properties = channel.CreateBasicProperties();
properties.Headers = new Dictionary<string, object>();
properties.Headers.Add("bytes", new byte[] { 0, 1, 2, 3 });
properties.Headers.Add("string", "testing");
```
And when you `BasicPublish` that message and look at the AMQP traffic, you'll see that both properties got encoded as a long string (S) in the headers field table.

Currently on the receiving end, they will all show up as byte arrays, but that does allow someone to receive an actual byte array if that's what they wanted in the header.

It seems like if you just change how long strings are decoded, you'd break anyone who is sending byte arrays intentionally, and this isn't just a breaking change, it's a break that prevents older clients and newer clients from talking to each other.

That's the point I'm trying to make by questioning making this change (as much as it makes sense) and why I was lamenting the `x` type not being used in https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/415#issuecomment-383121257.

Of course, you can totally decide this change is worth making, but it seems to me that it deserves more consideration than a regular "this is a new major so breaks are ok" type of change.

**Comment by lukebakken** [comment]
Based on the comment [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/198#issuecomment-236536391) by @kjnilsson and the comment [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/415#issuecomment-580422871) by @bording my inclination at this point is to leave the behavior as-is.

I will mark this issue with `next-gen-todo` so that it is not forgotten.

**Comment by Dewey623** [comment]
@michaelklishin https://stackdev.space/questions/converting-byte-arrays-to-strings-in-c
