### ISSUE TITLE
Get the BrokerUnreachableException

### ISSUE THREAD

**Issue by chjxidian** [rabbitmq/rabbitmq-dotnet-client#416]
Hi :

I have got the BrokerUnreachableException : "None of the specified endpoints were reachable" when I create a connection.
Please help me !

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [server logs](http://www.rabbitmq.com/logging.html#connection-lifecycle-events) and [start with the network troubleshooting guide](http://www.rabbitmq.com/troubleshooting-networking.html).
