### ISSUE TITLE
RabbitServer log:missed heartbeats from client   rabbitClient log: Unexpected Exception

### ISSUE THREAD

**Issue by thicktao** [rabbitmq/rabbitmq-dotnet-client#430]
hi， i have a problem in my Environment，my receive connection often disconnects the rabbitserver. The rabbitmq server log like this :missed heartbeats from client 10s  ； And my receive program will fire ModelShutdown event and Shutdown event . I don't known how it happened. and the important thing is that why the client  can't reconnect .  my config like this : 
 Factory.AutomaticRecoveryEnabled = true; 
Factory.AutomaticRecoveryEnabled = true;
can you help me ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much with the amount of information provided. See [Troubleshooting Networking](http://www.rabbitmq.com/troubleshooting-networking.html), take a [traffic capture](http://www.rabbitmq.com/amqp-wireshark.html) and perhaps mention the version of the client used when you post to the list.
