### ISSUE TITLE
Declaring an internal exchange.

### ISSUE THREAD

**Issue by mikalaiblr** [rabbitmq/rabbitmq-dotnet-client#432]
There is the following method available for declaring an exchange: 

```
[AmqpMethodDoNotImplement(null)]
void ExchangeDeclare(string exchange, string type, bool durable, bool autoDelete, IDictionary<string, object> arguments)
```

[Docs](http://rabbitmq.github.io/rabbitmq-dotnet-client/api/RabbitMQ.Client.IModel.html#RabbitMQ_Client_IModel_ExchangeDeclare_System_String_System_String_System_Boolean_System_Boolean_System_Collections_Generic_IDictionary_System_String_System_Object__) say: 
> The exchange is declared non-passive and non-internal. The "nowait" option is not exercised.

Is there is the way to declare an internal exchange (e.g. dead letter exchange)?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Internal exchanges cannot and are not meant to be declared or used by applications. They exist for plugins such as Federation.
