### ISSUE TITLE
Disposed model doesn't release resources

### ISSUE THREAD

**Issue by paulomorgado** [rabbitmq/rabbitmq-dotnet-client#434]
I have some code like this:

```
bool result;

using (var model = this.connection.CreateModel())
{
    var tcs = new TaskCompletionSource<bool>();

    model.ConfirmSelect();
    model.BasicAcks += (s, e) => tcs.TrySetResult(true);
    model.BasicReturn += (s, e) =>
    {
        if (e.BasicProperties.CorrelationId == correlationId)
        {
            tcs.TrySetResult(false);
        }
    };

    var props = model.CreateBasicProperties();
    // set properties

    model.BasicPublish(exchange: ExchangeName, routingKey: uid, mandatory: true, basicProperties: props, body: body);

    result = await tcs.Task;
}
```

But this code seems to not release all the resources and I end up with leaked `AutorecoveringModel`.

Shouldn't `Dispose` (or `Abort`) cleanup all resources?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
@paulomorgado we would really appreciate if you posted questions to `rabbitmq-users` and not filed them as issues as long as there's enough evidence of something that can/should be addressed in the client and a way to reproduce. I don't think this is the first time when we asked for this.

**Comment by michaelklishin** [comment]
It's not clear what specifically does "resources" mean here. Closing a channel (`IModel`) will not close its connection, for example. This is mailing list material.
