### ISSUE TITLE
rabbitmq-dotnet-client can't build

### ISSUE THREAD

**Issue by TANZAME** [rabbitmq/rabbitmq-dotnet-client#491]
there are some error when build src use vs2017, warning that autogenerated-api-0-9-1.cs not found,how can I resolve that ?

**Comment by zgabi** [comment]
Run the build.bat from the root folder. It will generate that file.

But I think it is very strange that you have to do this manually. This should be automatically executed when you build from VS.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This client uses code generation. This question should be covered in [BUILDING_DOTNET_CORE.md](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/BUILD_DOTNET_CORE.md) and [RUNNING_TESTS.md](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/RUNNING_TESTS.md).
