### ISSUE TITLE
Does rabbitmq support .net framework 3.5 ?

### ISSUE THREAD

**Issue by SHocker-Yu** [rabbitmq/rabbitmq-dotnet-client#492]
.net framework version: 3.5
erlang version: 21.0.1
OS: win7 64bit
VS: 2015

Hi, i'm using the version 3.5 of .net framework, im looking for the version of rabbitmq supporting it, but i failed, so i has to ask this question in here, I would appreciate it  if somebody could give me some suggest about this question.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by SHocker-Yu** [comment]
@michaelklishin Sorry and Thank You

**Comment by michaelklishin** [comment]
From the [.NET client guide](http://www.rabbitmq.com/dotnet-api-guide.html):

```
4.x and 5.x release series of this library require .NET 4.5.1+ or
a .NET Standard 1.5+ implementation (e.g. .NET Core 2.x).
```

The same requirements are mentioned in the [README](https://github.com/rabbitmq/rabbitmq-dotnet-client/#supported-platforms-and-net-releases).

A mailing list archive search suggests that the [last version to support .NET 3.5 is 3.4.3](https://groups.google.com/d/msg/rabbitmq-users/Zb-vpIQdcHA/eZ1VDFmWBAAJ).

**Comment by SHocker-Yu** [comment]
@michaelklishin Really appreciate your help!
