### ISSUE TITLE
QueueUnbind behavior when there are active consumers exists

### ISSUE THREAD

**Issue by cilerler** [rabbitmq/rabbitmq-dotnet-client#497]
I saw [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs#L56-L58) that they used `.QueueUnbind` upon subscription close.  

I started to wonder what will happen if there are multiple instances.  Tried to locate what does `.QueueUnbind` code in this repository but no luck _(too many circles)_.  

So my question is, is that only going to unbind if there is no consumer left? Or is it going to unbind it even there is an existing active consumer?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Bindings are orthogonal to consumers. You can delete all bindings without cancelling any consumers. Their queues won't see any more messages routed to them but it doesn't cancel consumers or in any way contradict the fact that they are still around.

If a consumer has to stop but the queue is not going away, deleting any bindings set up by that consumer [app] is a good idea but isn't a requirement. As long as you don't leak bindings do whatever you think make sense. Of course deleting a queue will delete all its bindings.
