### ISSUE TITLE
Client hang during TLS negotiation

### ISSUE THREAD

**Issue by rwkarg** [rabbitmq/rabbitmq-dotnet-client#501]
Generally we get good error messaging when connections don't get made but we ran in to a case where the client just hangs, never proceeds and logs nothing.

We had a case of asyemmetric BGP routing between data centers that resulted in the socket opening but the TLS negotiation packets from the broker were not successfully sent back to the client. The client then hung at the below line waiting for the connection to complete. No logging, not exception, no timeout.

We've temporarily address this by having our wrapper library wrap all CreateConnection lines with a timeout using the following pattern:
```
        private static void CreateConnectionWithTimeout(ConnectionContainer container, TimeSpan timeout)
        {
            var timeoutTask = Task.Delay(timeout);
            var connectionTask = Task.Run(() =>
            {
                var connection = container.Factory.CreateConnection();
                if (timeoutTask.IsCompleted)
                    throw new TimeoutException();
                return connection;
            });
            

            Task.WaitAny(timeoutTask, connectionTask);

            if (!connectionTask.IsCompleted)
                throw new BrokerUnreachableException(
                    new TimeoutException(
                        $"Connection attempt was not complete after {(int) timeout.TotalMilliseconds} ms."));
            else
            {
                container.Connection = connectionTask.Result;
            }
        }
```

Here's the line in the client where it was hanging:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/4ba8eaa29fb87f3276071b73d70b5774d0a6a0fd/projects/client/RabbitMQ.Client/src/client/api/SslHelper.cs#L77

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There can be any number of reasons why a TLS stream operation could hang. The client cannot be responsible for them.

If there's a missing timeout to that specific call or a known and recommended way to apply timeouts to `SslStream` operations, we'd definitely consider a pull request. Otherwise, I'm afraid there is not enough information here to suggest much and this is mailing list material.

**Comment by MZar2019** [comment]
This might help someone.

I just resolved a similar issue, this was my problem and my chosen solution.

[Big delay when calling SslStream.AuthenticateAsClient](https://docs.microsoft.com/en-us/archive/blogs/alejacma/big-delay-when-calling-sslstream-authenticateasclient)

[Turn Off Automatic Root Certificates Update](https://stackoverflow.com/questions/17463105/how-to-set-group-policy-turn-off-automatic-root-certificates-update-vie-regist)

**Comment by michaelklishin** [comment]
Thank you for sharing those, @MZar2019!
