### ISSUE TITLE
Cannot consume multiple messages in parallel

### ISSUE THREAD

**Issue by CSharpBender** [rabbitmq/rabbitmq-dotnet-client#506]
I've just started playing with RabbitMQ.Client 5.1.0 and I've noticed I can't consume multiple messages in parallel.
I'm using a single IModel instance with prefetchCount=10 and multiple consumers with AsyncEventingBasicConsumer. In the event handler I'm simulating a long running operation: await Task.Delay(5000).
I've noticed that a single message gets processed every 5 seconds although I have multiple consumers.
If I don't await for my method (fire and forget) then the messages are processed in parallel as expected.

Question: 
1) Is this the intended behavior, a synchronous message processing that allows me to await for async methods?
2) Is there a problem if I use a single IModel listening for messages and doing Ack/Nack/Reject on multiple Threads? I know IModel is not thread safe for publishing but what about consuming messages?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
1. Deliveries are dispatched to a consumer operation pool with the per-channel ordering guarantee. This guarantee is preserved with the asynchronous dispatcher. If you expect operations to block, consider using more channels or moving work away from the dispatch thread(s).
2. Has been many times before on the mailing list. Acknowledging a single message concurrently can be safe (as long as it's on the channel of delivery and there are no double acks). Acknowledging with `multiple = true` concurrently will result in [double acks](http://www.rabbitmq.com/confirms.html#consumer-acks-double-acking) and thus channel-level exceptions.
