### ISSUE TITLE
Design question related to VirtualHost definition

### ISSUE THREAD

**Issue by cilerler** [rabbitmq/rabbitmq-dotnet-client#509]
I wonder why `VirtualHost` definition is in the `ConnectionFactory` and not in the `ExchangeDeclare`, `QueueDeclare` and `QueueBind` or simply part of `IModel`?

As you may see below `vhost` is part of those objects

## Partial RabbitMQ export

```json
{
    //...
    "exchanges": [
      {
        "name": "brainiac.topic",
        "vhost": "/",
        "type": "topic",
        "durable": true,
        "auto_delete": false,
        "internal": false,
        "arguments": {}
      }
    ],
    "queues": [
      {
        "name": "brainiac.Ensurer",
        "vhost": "/",
        "durable": true,
        "auto_delete": false,
        "arguments": { "x-message-ttl": 180000 }
      }
    ],
    "bindings": [
      {
        "source": "brainiac.topic",
        "vhost": "/",
        "destination": "brainiac.Ensurer",
        "destination_type": "queue",
        "routing_key": "#",
        "arguments": {}
      }
    ]
    //...
}
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Covered by the [Connections](https://www.rabbitmq.com/connections.html) and [Virtual Host](https://www.rabbitmq.com/vhosts.html) doc guides. Entities are contained within virtual hosts which is specified at connection time. A single connection is limited to a single vhost. Channels are not related to virtual hosts other via their connection.

What HTTP API responses or eported definitions look like doesn't change that.
