### ISSUE TITLE
Does rabbitmq client support a connection via STOMP rabbitmq port?

### ISSUE THREAD

**Issue by brunohenriquepj** [rabbitmq/rabbitmq-dotnet-client#511]
I'm new on rabbitmq and I'm developing a publisher and consumer in dotnet core. But on the server I'm trying to connect, there is only the stomp port open. I researched on doc and web, but I don't see anything about connect on rabbitmq server by stomp port using dotnet client, only amqp.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
If you plan on using STOMP you need a .NET STOMP client. This one implements AMQP 0-9-1.
