### ISSUE TITLE
Channel related

### ISSUE THREAD

**Issue by tamer-akkaya** [rabbitmq/rabbitmq-dotnet-client#645]
Hello Mr/Mrs.
I am using your .Net Client v5.0. In my Windows Service app, I use one connection and two channels for sending and receiving messages, respectively. I have realized that the sending channel somehow gets closed even if the connection is up and the receiving channel is also running. More interestingly, when I send a message to itself in order to test the connection at realtime, it receives the message while the receiving channel is already disposed. I have confirmed that the receiving channel is disposed via RabbitMQ Web Interface, either. I had to use this kind of testing method (sending a message itself), just because the 'IsClosed' variable of the channel returns true. Whereas, there is no channel open at that moment. 

Could you help me with this issue, please?

Sincerely, 
Tamer Akkaya

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ or the client do not close channels except for when the connection is closed or [there is a channel-level exception](https://www.rabbitmq.com/channels.html#error-handling). See [server logs](https://www.rabbitmq.com/logging.html) to find out what it is.

On top of that, deliveries are dispatched to a work pool and thus will happen concurrently with channel closures. Therefore it is possible that a delivery is still processed but the channel is then closed.

I don't have any evidence provided but my gut feeling is that you are running into a [double acknowledgement error](https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking) on the consumer end.
