### ISSUE TITLE
What is the substitute for `ISubscription` and `Subscription`?

### ISSUE THREAD

**Issue by babakarj** [rabbitmq/rabbitmq-dotnet-client#659]
Updating **RabbitMQ.Client** to version **5.1.1**. What is the substitute for `ISubscription` and `Subscription`?

Warnings:
'ISubscription' is obsolete: 'Messaging patterns are no longer recommended for use and will be removed.' 
'Subscription' is obsolete: 'Messaging patterns are no longer recommended for use and will be removed.'

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Any consumer implementation you like. `DefaultBasicConsumer`, `AsyncDefaultBasicConsumer` or your own reincarnation of `Subscription` on top of those (I'm kidding, it's a terrible pattern that does not work well with automatic connection recovery for a reason).

See [RabbitMQ tutorials](https://www.rabbitmq.com/getstarted.html) if you have never used a "regular" consumer before.
