### ISSUE TITLE
Multiple connections/channels in the same thread/context failing

### ISSUE THREAD

**Issue by breno601** [rabbitmq/rabbitmq-dotnet-client#661]
I have an ASP.NET MVC Application and 2 packages with a Service each using RabbitMQ Client to connect to the same broker, although each creates a connection and channel (both non-static). Each service is a singleton in the MVC application, and both enqueue messages to their respective queues.

The problem starts when, using the two services (A and B) in the same context/class, when I call A.EnqueueX, all the Enqueues for service B stop working (and only enqueues for Service A work). If I do the other way around, calling enqueue from service B first, it would work but then enqueues from A would not work. Meaning the enqueue only works for the first service I call!

Extra information: 
- The clients declared in the packages/services are not static. 
- We are using regular injection in the MVC Context (declaring private readonly interface and injecting via constructor)

Example:
```

public string Execute() {
    _serviceA.EnqueueX(1); // Works
    _serviceB.EnqueueY(2); // Doesn't work
    ...
    _service.EnqueueX(3); // Work
    _service.EnqueueY(4);  // Doesn't work
}

```

Any help is very much appreciated.

Thanks!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much without seeing the code and server logs. The right place to share those is on the mailing list. There is a doc section dedicated to [Troubleshooting publishers](https://www.rabbitmq.com/publishers.html#troubleshooting).
