### ISSUE TITLE
(un)signed shorts in table serialisation

### ISSUE THREAD

**Issue by visander** [rabbitmq/rabbitmq-dotnet-client#662]
We would like to use an official release for our RabbitMQ library and in the latest stable version 5.1.2 the (un)signed shorts are missing in ReadFieldValue in WireFormatting.cs

Is this planned for a future release?

**Comment by michaelklishin** [comment]
Before you draw any conclusions about what table field types are supported or not, see the [Protocol Errata](https://www.rabbitmq.com/amqp-0-9-1-errata.html#section_3) section.

This client is over a decade old, so we can confidently tell that some field types are basically irrelevant, possibly because there is no meaningful representation of those types in languages such as Python or JavaScript.

We would consider a PR for anything that's missing.

**Comment by visander** [comment]
Thanks for the fast reply. 

The errate you mention states that Rabbit supports these two types:
        U       s            Signed 16-bit      (A1)
        u       u            Unsigned 16-bit

From this draw the conclusion that it is missing in the dotnet implementation. Or did I miss something?

**Comment by michaelklishin** [comment]
`s` [is present](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/WireFormatting.cs#L159) in `ReadFieldValue` :

``` csharp
case 's':
                    value = reader.ReadInt16();
                    break;
```

`u` is not.

**Comment by visander** [comment]
My apologizes, I missed that one.
Will the unsigned short also be implemented then?

**Comment by michaelklishin** [comment]
@visander as I said this field has been missing for a decade and this is the first time in about seven years that I see it brought up (at least for this client). However, this is open source software. You are welcome to implement it.
