### ISSUE TITLE
Model.QueueDeclare hangs forever

### ISSUE THREAD

**Issue by vasily-kirichenko** [rabbitmq/rabbitmq-dotnet-client#79]
![image](https://cloud.githubusercontent.com/assets/873919/7385748/c2844b04-ee53-11e4-8433-27cb29c3da95.png)

The process has single thread running and it's stuck in the above state forever (at least hours).
How I can investigate the issue further?

**Comment by michaelklishin** [comment]
Either you have a resource alarm (so RabbitMQ stops reading from the socket), or your client is connected to a mirror and there was a network split with master on the opposite side of it. Both cases should be visible in the logs.

We should introduce continuation timeouts, since it's a lot easier to do for C#, which doesn't have the misfortune of checked [timeout] exceptions.
