### ISSUE TITLE
Constants are no longer visible

### ISSUE THREAD

**Issue by danlyons-softek** [rabbitmq/rabbitmq-dotnet-client#819]
As part of streamlining the public API surface in #714, the RabbitMQ.Client.Framing.Constants type was made internal.  However, it is still referenced in the API documentation for [ShutdownEventArgs.ReplyCode](http://rabbitmq.github.io/rabbitmq-dotnet-client/api/RabbitMQ.Client.ShutdownEventArgs.html#RabbitMQ_Client_ShutdownEventArgs_ReplyCode).

It should probably be made public again (possibly moving it to a different namespace - e.g., [RabbitMQ.Client.Constants](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/714#issuecomment-615349987)) or replaced with something else.

**Comment by bording** [comment]
As I just commented on https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/714#issuecomment-615374098, ReplyCode should be an `enum` instead of needing a separate class to interpret the values.

Of course changing that now would be a breaking change, so I guess in the mean time, opening that class back up is a short-term fix.

**Comment by lukebakken** [comment]
@danlyons-softek @goldenbull - we'd be happy to review a pull request to implement this suggestion:

> so I guess in the mean time, opening that class back up is a short-term fix.

I may or may not have time to get to it soon.
