### ISSUE TITLE
Message stuck in rabbitmq

### ISSUE THREAD

**Issue by snazzypramod** [rabbitmq/rabbitmq-dotnet-client#856]
I am using RabbitMQ.Client(5.2.0) for .net. I am able to consume those messages. But at some point, messages got stuck into RabbitMQ in the production environment. When I restart my .net core application then it starts working. 
After searching on google I came to know that I need to introduce heartbeat property. I made those changes as well, but still facing the same issue. 
The biggest problem is I am not able to reproduce this issue in a local or dev environment. In RabbitMQ console ui consumer count is 4 and 2 messages got stuck. Please help me.

`ConnectionFactory factory = new ConnectionFactory
            {
                Uri = new Uri(connectionString),
                AutomaticRecoveryEnabled = true,
                NetworkRecoveryInterval = TimeSpan.FromSeconds(5),
                RequestedHeartbeat = 60
            };`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much with the amount of information provided. Please consult and share your application's logs and server logs as well on the list.

Besides [heartbeats](https://www.rabbitmq.com/heartbeats.html), [channel errors](https://www.rabbitmq.com/channels.html#error-handling) is a mandatory doc section to read, together with

 * [Connection recovery of consumers](https://www.rabbitmq.com/consumers.html#connection-recovery)
 * [Connection lifecycle events](https://www.rabbitmq.com/logging.html#connection-lifecycle-events)
 * The entire guide on [confirms and data safety](https://www.rabbitmq.com/confirms.html), in particular [client errors due to incorrect acknowledgment](https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking)
 * [Unroutable message handling](https://www.rabbitmq.com/publishers.html#unroutable)
 * Publisher-side [data safety](https://www.rabbitmq.com/publishers.html#data-safety)

If you don't have queue and consumer metrics or logs, instead of looking for a quick fix, ask yourself, what could lead to "stuck messages". Some very common scenarios are

 * Client connection loss
 * TCP connection disruption that takes a while to detect (and heartbeats speed up)
 * Channel-level exceptions, including those stemming from incorrect acknowledgments
 * Consumer exceptions that render consumers incapable of processing further deliveries
 * Unroutable messages
 * Fire-and-forget publishing

Many of these events will be visible in the logs, others can be detected using metrics of both RabbitMQ and your own code, or additional logging of exceptions in your consumers.

Don't guess, collect relevant data and form a hypothesis that can be verified, then another one, and so on.

**Comment by michaelklishin** [comment]
Also, it would be extremely helpful to know what a "stuck" message means. It may be obvious to you but it's not at all obvious to others. Was a message delivered and not acknowledged? That would be easy to see from queue metrics. Are messages sitting there in ready state and not being delivered? This would also show up in the metrics. Is there a prefetch limit on the channel? If so, has it been exhausted (equal to the number of delivered but unacknowledged messages)? Metrics can provide an answer to that, too.

This is the kind of questions and data that will lead you to understanding of what's going on, and only then you would be able to address it.
