### ISSUE TITLE
RabbitMqConsumer does not process messages in parallel

### ISSUE THREAD

**Issue by ig-sinicyn** [rabbitmq/rabbitmq-dotnet-client#875]
RabbitMq.Client: 6.1.0

We have a [sample](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4803111/ConsoleApp1.zip) that imitates slow consumers with manual ack logic.
Auto-ack is not applicable in our case as we need to send unprocessable messages to the deadletter exchange.

Console output shows that messages are processed one-by-one,
```
00:00:01.0399574 Begin process 1
00:00:01.5405516 End process 1
00:00:01.5409783 Begin process 8
00:00:02.0405927 End process 8
00:00:02.0409129 Begin process 5
00:00:02.5413952 End process 5
00:00:02.5417483 Begin process 6
00:00:03.0423456 End process 6
```
I've tried both AsyncEventingBasicConsumer and EventingBasicConsumer, no change in behavior.

[Documentation](https://www.rabbitmq.com/dotnet-api-guide.html#consumer-callbacks-and-ordering) states that
>IBasicConsumer callbacks are invoked concurrently. However, per-channel operation order is preserved. In other word, if messages A and B were delivered in this order on the same channel, they will be processed in this order. 

but this looks like a major limitation for achieving high throughput. 

We've estimated amount of work required to handle parrallel workloads in a correct way and it is not an easy thing.
In effect, we'll need to write own IBasicConsumer implementation that will enqueue events to the worker pool, pause enqueuing if the pool is full and perform correct shutdown (including nacks on runnings tasks) on consumer dispose / cancel.

If there is a sample or guideline for such thing it will be a great help for us.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
@ig-sinicyn sequential per-channel ordering is by design and is not going to change. The absolute majority of users expect such an ordering guarantee and will complain loudly if we stop providing it. If you want more parallelism, you can always dispatch actual processing to a thread pool, use more channels, and so on. The entire point of having a consumer interface implementation is that no size fits all.

Our team does not use GitHub issues for discussions.

**Comment by michaelklishin** [comment]
It's worth mentioning that this is a [.NET port](https://github.com/rabbitmq/rabbitmq-dotnet-perf-test) of [PerfTest](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/) which can be used as-is or modified instead of producing benchmarks from scratch.

**Comment by ig-sinicyn** [comment]
[Reposted](https://groups.google.com/forum/?oldui=1#!topic/rabbitmq-users/4n3jeqmzpV4)

**Comment by ig-sinicyn** [comment]
> It's worth mentioning that this is a .NET port of PerfTest which can be used as-is or modified instead of producing benchmarks from scratch.

These are in f#, not c#. Also, they are not close to the real-life scenarios. No async code, no delivery confirms, no persistence etc.

**Comment by michaelklishin** [comment]
Apparently the .NET port is a lot more of a proof-of-concept than I'd realized. Oh well.

**Comment by darraghjones** [comment]
At the very least the documentation is unclear. I'm not sure what this sentence even means:

> Consumer callbacks are invoked in tasks dispatched a [TaskScheduler](https://msdn.microsoft.com/en-us/library/dd997402%28v=vs.110%29.aspx).

**Comment by lukebakken** [comment]
@darraghjones would you mind starting a [discussion](https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions) with your specific question and how it relates to parallel consumer dispatch? We're always looking for ways to make this library easier to use. Thank you.
