### ISSUE TITLE
AsyncEventingBasicConsumer not working for me

### ISSUE THREAD

**Issue by nperepichka** [rabbitmq/rabbitmq-dotnet-client#948]
```
var consumer = new AsyncEventingBasicConsumer(channelInfo.Channel);
consumer.Received += async (co, ea) =>
{
    //this action newer executed and I don't see consumers in web portal
    await Task.Delay(10);
};
channelInfo.Channel.BasicConsume(listenDefinition.Queue, false, consumer);
```

but EventingBasicConsumer works witout issues:
```
var consumer = new EventingBasicConsumer(channelInfo.Channel);
consumer.Received += (co, ea) =>
{
    Thread.Sleep(10);
};
channelInfo.Channel.BasicConsume(listenDefinition.Queue, false, consumer);
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [AsyncEventingBasicConsumer test suite](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/275b4ebcc6f00df414612703ea0c3e367f233c26/projects/Unit/TestAsyncConsumer.cs). It instantiates a connection factoring using

``` csharp
var cf = new ConnectionFactory{ DispatchConsumersAsync = true };
```
