### ISSUE TITLE
CredentialsProvider for OAuth2 authentication?

### ISSUE THREAD

**Issue by moanrose** [rabbitmq/rabbitmq-dotnet-client#955]
Hi

What is the plan for porting the `CredentialsProvider` from the Java Client to the .NET client?

I would like to use OAuth2 as auth mechanism for RabbitMQ. Either using https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2 or as in my case - the HTTP Auth Backend with a custom OAuth2 token validator.

However the current implementation of the ConnectionFactory only allows for a static set of credentials. I Can see that support for OAuth tokens, and token refresh has been implemented in the Java client using the CredentialsProvider abstraction.

**Comment by michaelklishin** [comment]
The plan for every feature is that someone (maybe a RabbitMQ core team member, maybe not) will contribute it and the core team will consider it. This is open source software after all.

Let's take a step back and understand what's involved in "OAuth 2 support". On the client side, a JWT token has to be provided in the password field. The username will be ignored (all relevant information will be taken from the decoded token).
You can make such a connection today, there's nothing to change in the client.

However, JWT tokens have limited shelf life. When they expire, no operations performed by a client will be accepted as token validation will fail. Since the protocols RabbitMQ supports assume long lived connections, there has to be a refresh mechanism. OAuth 2 clients have a different token, called the refresh token, that can be used to obtain a new JWT token with a refreshed expiration period.

In the Java client, `CredentialsProvider` is an interface that allows for the end user to provide a "refresh function" that, in the case of OAuth 2, will use a suitable OAuth 2 vendor client library and a refresh token to produce a new token and replace it on a connection. `connection.update-secret` is a new protocol extension for AMQP 0-9-1 that makes it possible
to update the token for an already open connection.

**Comment by michaelklishin** [comment]
I will file a specific issue about what has to happen in this client.

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/956.
