### ISSUE TITLE
RPC client side multithread, message sent twice with same correlationid

### ISSUE THREAD

**Issue by nicoclau** [rabbitmq/rabbitmq-dotnet-client#957]
Hello in C#

in RPC design on client side I use multithreads:

- I use one thread per request which creates each time one correlationid and one channel IModel
- I use a  ConcurrentDictionary<Guid, IModel> for keeping associated each correlationid with each IModel
- I use a ConcurrentDictionary<Guid, AsyncEventingBasicConsumer>  for keeping associated each correlationid with each consumer

I use a lock on connection around this code

lock (_rabbitMQPersistentConnection)
            {
 var asyncEventingBasicConsumer = new AsyncEventingBasicConsumer(channel);
                asyncEventingBasicConsumer.Received += async (ch, ea) =>
                {
                    await GetResponseAsync(ch, ea);
                };
                eventconsummers[correlationId] = asyncEventingBasicConsumer;
}

But Received is called twice for the same correlationid with deliverytag = 2 why?
Thanks for any help

Can you explain me how deliverytag is incremented, is it because it is the same channel which receive 2 messages? (edited)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much without a complete code example. A single message can be routed to more than one queue. A single message can be published N times by the publisher. A single message **certainly cannot be consumed more than once** (without being requeued and redelivered, that is).

**Comment by michaelklishin** [comment]
Delivery tag is incremented by RabbitMQ channels when they deliver messages. If you see it incremented twice it means that a channel has actually delivered two messages. A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) can be used to confirm this hypothesis, as can [RabbitMQ Firehose](https://www.rabbitmq.com/firehose.html).

**Comment by nicoclau** [comment]
Thanks Michael for your kind help
