### ISSUE TITLE
"Object reference not set to an instance of an object" when connecting using Ssl.Enabled = true

### ISSUE THREAD

**Issue by danielsvalefelt** [rabbitmq/rabbitmq-dotnet-client#974]
**Description**
I do not know exactly what happens (I am struggling to understand the SSL settings), but the problem is that, SslHelper.TcpUpgrade throws an exception in SocketFrameHandler constructor, it is calling Close(), but _writerTask is not created yet.

Close calling GetResult without checking.

So, basically, you get a "Object reference not set to an instance of an object" instead of the real exception..

**Solution:**
Change:
_writerTask.GetAwaiter().GetResult(); 
to
_writerTask?.GetAwaiter().GetResult();

**Comment by michaelklishin** [comment]
We cannot conclude whether this will be a "solution" or just mask an exception without understanding what's going on. Please submit pull requests instead of suggesting changes in an issue.

RabbitMQ has a dedicated doc guide that explains how to [narrow down TLS connectivity issues](https://www.rabbitmq.com/troubleshooting-ssl.html), and an extensive [TLS guide](https://www.rabbitmq.com/ssl.html) which explains the basics of TLS, including how peer verification is performed.

There really isn't much else that can be suggested with this much information. We do not guess in this community.
