### ISSUE TITLE
Object reference not set to an instance of an object" when connecting using Ssl.Enabled = true

### ISSUE THREAD

**Issue by danielsvalefelt** [rabbitmq/rabbitmq-dotnet-client#975]
The following code sample is generating "Object reference not set to an instance of an object".

            var connectionFactory = new ConnectionFactory();
            connectionFactory.UserName = "myUser";
            connectionFactory.HostName = "myHost";
            connectionFactory.Password = "myPassowrd";
            connectionFactory.Ssl.Enabled = true;
            var connection = connectionFactory.CreateConnection();

The underlying problem is most likely a misconfiguration of my SSL settings, and the system is probably correctly throwing an exception, but it is unlikely that it should throw "Object reference not set to an instance of an object" by design.

The problem is most likely that _writerTask is not yet initialized, and the catch-clause is calling Close(), and Close is not checking if _writerTask is null.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid a few lines of code do not really clarify much compared to #974. We do not have enough information in order to be confident as to what is going on:

 * No [server logs](https://www.rabbitmq.com/logging.html) to try to understand why exactly connections fail
 * No executable example to run
 * No complete stack trace

Consider starting a mailing list thread or putting together and sharing a runnable example repository that use a pair of [self-signed TLS certificates](https://github.com/michaelklishin/tls-gen). All we can do right now is guess as to what is happening in your system. Guessing is too risky and really time-consuming for everyone involved.

**Comment by michaelklishin** [comment]
Instead of mentioning variable and method names, consider linking to source code here on GitHub. The entire codebase is open source.

I'll assume that [this is the line](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/impl/SocketFrameHandler.cs#L196). If a socket frame handler is being closed, there isn't much we can do in case of unexpected exceptions.

However, it would be very nice to understand what code path leads to the method in question. A connection can be closed by the client or the server, explicitly or due to an error, authentication failure and so on.

**Comment by danielsvalefelt** [comment]
True.
And I do not think I would have put that code in the constructor in the first place, but either set up the connection and handed it over to the constructor when (and if) it is ready, or called a "connect" method once the constructor is done.

But I do not think this minor bug merits a refactoring, so I leave it over to you... I just started to use the code two days ago, and it works well for me (except this).
