### ISSUE TITLE
BasicCancelNoWait does not notify consumer 

### ISSUE THREAD

**Issue by bollhals** [rabbitmq/rabbitmq-dotnet-client#993]
While doing some refactoring I saw that if you call IModel.BasicCancelNoWait then it just sends the cancel and removes the consumer from the dictionary without ever notifying the consumer that it got cancelled.

BasicCancel triggers on received CancelOk => IBasicConsumer.HandleBasicCancelOk
On received Cancel => IBasicConsumer.HandleBasicCancel

Is it correct to not notify or should we call IBasicConsumer.HandleBasicCancel?

**Comment by michaelklishin** [comment]
`BasicCancelNoWait` is a way for the user to say "do this, I don't care about the result". It's a good question if the consumer should be notified because consumer cancellation notifications are supposed to be [server-triggered](https://www.rabbitmq.com/consumer-cancel.html). So this behavior makes sense to me.

**Comment by bollhals** [comment]
Question is, shall a `consumer` care about `Cancel` / `CancelOK` and whether is was server-triggered or just that it got cancelled?
If yes, then current behavior is correct and I'd close this issue.
If not, then I'd adapt to call a cancel method.

**Comment by michaelklishin** [comment]
Java client only calls `Consumer#handleCancel` when a `basic.cancel` frame is received from the server. I don't remember anyone complaining about this.

**Comment by bollhals** [comment]
Fine, then let's leave it as is =)
